server:
  port: 8081

logging:
  config: classpath:log/logback.xml
#  path: D:/log
  path: /Users/longjianyong/log

## mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/liao?serverTimezone=UTC &useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root

##hana
#spring:
#  datasource:
#    url: jdbc:sap://10.96.12.241:30015?reconnect=true
#    driverClassName: com.sap.db.jdbc.Driver
#    username: DEMO2
#    password: Aa123456

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.timeselectrical.model  # 注意：对应实体类的路径